# Site settings
title: Blog
description: "Hello, this is just a mind spew of some of my researched curiosities using AI and other resources."
baseurl: "/blog"
url: "https://jaydenxsoe.github.io"

# Social settings
email: ""
#twitter_username: jaydenxsoe
github_username:  jaydenxsoe

# Build settings
theme: minima
#plugins:
#  - jekyll-feed
#  - jekyll-seo-tag

# Build settings
#markdown: kramdown
#permalink: pretty
#
#highlighter: rouge
#kramdown:
#  input: GFM
#  auto_ids: true
#  syntax_highlighter: rouge
